openapi: 3.0.0
info:
  title: Enviroments API
  description: Main API of web application - Green Cyprus
  version: 0.0.0
paths:
  /project:
    post:
      summary: Create a new project
      operationId: createProject
      requestBody:
        description: Project object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: Project created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

  /project/{uuid}:
    get:
      summary: Get a specific project by UUID
      operationId: getProjectByUUID
      parameters:
        - name: uuid
          in: path
          description: UUID of the project to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Project not found

  /projects:
    get:
      summary: List all projects
      operationId: listProjects
      responses:
        '200':
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

  /polluted-area:
    post:
      summary: Create a new polluted area
      operationId: createPollutedArea
      requestBody:
        description: Polluted area object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PollutedArea'
      responses:
        '201':
          description: Polluted area created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PollutedArea'

  /polluted-area/{uuid}:
    get:
      summary: Get a specific polluted area by UUID
      operationId: getPollutedAreaByUUID
      parameters:
        - name: uuid
          in: path
          description: UUID of the polluted area to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Polluted area details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PollutedArea'
        '404':
          description: Polluted area not found

  /polluted-areas:
    get:
      summary: List all polluted areas
      operationId: listPollutedAreas
      responses:
        '200':
          description: A list of polluted areas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PollutedArea'

components:
  schemas:
    Project:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: 'd47e7f97-2f3b-4236-b234-e5c1f487f0bf'
        title:
          type: string
          example: 'Project lets green it'
        description:
          type: string
          example: 'A detailed description of the area problem.'
        created_by:
          type: string
          format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
        status:
          type: string
          example: 'active'
        location:
          type: string
          example: 'Paphos, CY'
        start_date:
          type: string
          format: date-time
          example: '2024-01-01T00:00:00Z'
        end_date:
          type: string
          format: date-time
          example: '2024-12-31T23:59:59Z'
        created_at:
          type: string
          format: date-time
          example: '2024-01-01T12:00:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2024-06-01T15:30:00Z'
      required:
        - title
        - description
        - created_by
        - start_date
        - end_date
        - location

    PollutedArea:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: 'd47e7f97-2f3b-4236-b234-e5c1f487f0bf'
        project_uuid:
          type: string
          format: uuid
          example: 'd47e7f97-2f3b-4236-b234-e5c1f487f0bf'
        type_of_pollution:
          type: string
          example: 'soil'
        pollution_level:
          type: string
          example: 'high'
        description:
          type: string
          example: 'Heavy industrial soil pollution affecting nearby communities.'
        location:
          type: string
          example: 'Nicosia, CY'
        created_at:
          type: string
          format: date-time
          example: '2024-03-15T10:00:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2024-06-10T18:45:00Z'
      required:
        - project_uuid
        - type_of_pollution
        - pollution_level
        - description
        - location
